# Generated by Django 3.0 on 2020-11-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201115_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='updated',
        ),
    ]
