# Generated by Django 3.0 on 2020-11-15 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201115_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
