# Generated by Django 3.0 on 2020-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201115_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
